# Add application configuration variables here, as shown below.
#
 FACEBOOK_APP_ID: 1499407516956382 #id
# PUSHER_KEY: 7381a978f7dd7f9a1117
 FACEBOOK_KEY: "e19b9251621185077f5e52038a250116" #secret
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
